[build]
  functions = "functions/"
  publish = "dist/"
  command = "npm run build"

[template.environment]
  VITE_APIKEY=AIzaSyB9EunLbLYlOCbveWiSVVmvxdbQXm6SlXI
  VITE_authDomain=orion-soft.firebaseapp.com
  VITE_databaseURL=https://orion-soft-default-rtdb.firebaseio.com
  VITE_projectId=orion-soft
  VITE_storageBucket=orion-soft.appspot.com
  VITE_messagingSenderId=890826928910
  VITE_appId=1:890826928910:web:bca1bd472541b2d362dd5f
  VITE_measurementId=G-HX3425DC19