export const customProduct = [
  {
    modelBase: 303,
    variant: 'normal',
    cuero: 'oscaria grabado',
    colores: ['negro, café'],
    precioBase: 115,
    adicionales: {
      costra: true,
      acero: true,
      aleteado: false,
      graso: false,
    },
  },
];
export const products = [
  {
    nombre: '304',
    modeloBase: '303',
    variante: 'estandar',
    forro: 'castor',
    cuero: 'oscaria grabado',
    colores: ['café', 'negro'],
    costra: true,
    dielectrico: false,
    acero: true,
    aleteado: true,
    plantillaAcero: false,
    plantillaPoliuretano: false,
    plantillaCastor: false,
    goma: 'RBBM2',
    precio: 136,
    img: '',
    adicional: '',
  },
  {
    nombre: '304 Max Arena',
    modeloBase: '303',
    variante: 'maximus arena',
    cuero: 'oscaria grabado',
    forro: 'castor',
    colores: ['café', 'negro'],
    costra: true,
    dielectrico: false,
    acero: true,
    aleteado: true,
    plantillaAcero: false,
    plantillaPoliuretano: false,
    plantillaCastor: false,
    goma: 'MAX ARENA',
    precio: 142,
    img: '',
    adicional: '',
  },
  {
    nombre: '303 económico',
    modeloBase: '303',
    variante: 'economico',
    cuero: 'oscaria grabado',
    forro: '',
    colores: ['café', 'negro'],
    costra: false,
    acero: false,
    aleteado: false,
    plantillaAcero: false,
    plantillaPoliuretano: false,
    plantillaCastor: false,
    goma: 'RBBM2',
    precio: 115,
    img: '',
    adicional: 'lengueta castor',
  },
  {
    nombre: 'Táctico',
    modeloBase: '510',
    variante: 'estandar',
    cuero: 'hunting',
    forro: 'castor',
    colores: ['arena'],
    costra: true,
    acero: true,
    dielectrico: false,
    aleteado: false,
    plantillaAcero: false,
    plantillaPoliuretano: false,
    plantillaCastor: true,
    goma: 'MAX ARENA',
    precio: 159,
    img: '',
    adicional: '',
  },
  {
    nombre: '407 dieléctrico',
    modeloBase: '407',
    variante: 'dieléctrico',
    cuero: 'liso industrial',
    forro: 'cuero nappa',
    colores: ['bic negro/cafe', 'café', 'negro', 'canela'],
    costra: true,
    dielectrico: true,
    acero: false,
    aleteado: false,
    plantillaAcero: false,
    plantillaPoliuretano: true,
    plantillaCastor: true,
    goma: 'RBBM2',
    precio: 185,
    img: '',
    adicional: 'cuello de cuero, lengueta cuero suave, lengueta acolchada',
  },
];
